version: '3.8'

services:

  db:
    image: postgres:12.4
    volumes:
      - ./storage/postgres/data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - moves_network

  redis:
    image: redis
    restart: always
    env_file:
      - .env
    volumes:
    - ./storage/redis/data:/data
    ports:
    - ${REDIS_PORT}:6379
    networks:
      - moves_network

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
    - "6831:6831/udp"
    - "16686:16686"
    networks:
      - moves_network

volumes:
  elastic_data:
  static_value:
  media_value:

networks:
  moves_network:
    name: moves_network
    external: true
