version: '3.8'

services:

  redis:
    image: redis
    container_name: redis_proxy
    restart: always
    env_file:
      - .env
    volumes:
    - ./storage/redis/data:/data
    command: --port 6378
    ports:
    - 6378:6378
    expose:
    - 6378
    networks:
      - moves_network

  auth_proxy_app:
    build: .
    restart: always
    volumes:
      - static_value:/code/static/
      - media_value:/code/media/
    env_file:
      - .env
    command: gunicorn auth_proxy_app.wsgi_app:app --bind 0.0.0.0:8001 --reload
    depends_on:
      - redis
    networks:
      - moves_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    image: nginx:1.19.3
    ports:
      - "8001:8001"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/

    depends_on:
      - auth_proxy_app
      - redis
    networks:
      - moves_network

volumes:
  static_value:
  media_value:

networks:
  moves_network:
    name: moves_network
    external: true
