version: '3.8'

services:

  redis:
    image: redis
    container_name: redis_proxy
    restart: always
    env_file:
      - .env
    volumes:
    - ./storage/redis/data:/data
    ports:
    - ${REDIS_PORT}:6379
    expose:
    - 6378
    networks:
      - moves_network

volumes:
  elastic_data:
  static_value:
  media_value:

networks:
  moves_network:
    name: moves_network
    external: true
